# Generated by Django 5.0.6 on 2024-05-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_calendar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
